_target_: src.models.tg_messages_module.TgCinderellaLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.text_linear_model.TextLinearModel
  vocab_size: 20000
  embed_dim: 1024
  num_class: 3
  num_linear: 4
